name: Hidden Face Test Workflow

on: [push, pull_request]

jobs:
  test-hidden-face:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Hidden Face Action
        uses: ./  # 현재 리포지토리에서 Action을 사용
        with:
          image_path: './images/test.jpg'

